name-template: "v$NEXT_PATCH_VERSION 🌟"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: ✨ Features
    labels: [enhancement]
  - title: 🐞 Fixes
    labels: [bug]
  - title: 🧱 Tasks
    labels: [task]
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
