services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ict
      POSTGRES_USER: ict
      POSTGRES_DB: ict
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
  vec:
    image: qdrant/qdrant:latest
    ports: ["6333:6333","6334:6334"]
    volumes:
      - qdrant_data:/qdrant/storage
  api:
    build: ./selector
    env_file: ./selector/.env.example
    depends_on: [db, vec]
    ports: ["8000:8000"]
    volumes:
      - ./selector:/app
volumes:
  db_data: {}
  qdrant_data: {}
