services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ict
      POSTGRES_USER: ict
      POSTGRES_DB: ict
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
  vec:
    image: qdrant/qdrant:latest
    ports: ["6333:6333","6334:6334"]
    volumes:
      - qdrant_data:/qdrant/storage
  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
  api:
    build: ./selector
    depends_on: [db, vec]
    ports: ["8000:8000"]
    volumes:
      - ./selector:/app
      - ./catalog:/app/catalog
    environment:
      - QWEN_API_KEY=${QWEN_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://vec:6333
      - CATALOG_CSV=/app/catalog/samples/products.csv
      - OLLAMA_BASE_URL=http://ollama:11434

  web:
    image: node:20-alpine
    working_dir: /web
    command: sh -c "npm i && npm run dev"
    ports: ["3000:3000"]
    environment:
      - NEXT_PUBLIC_API_BASE=http://api:8000
    volumes:
      - ./web:/web
    depends_on: [api]
volumes:
  db_data: {}
  qdrant_data: {}
  ollama_data: {}
